// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package demo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Query                *string  `protobuf:"bytes,1,req,name=query" json:"query,omitempty"`
	PageNumber           *int32   `protobuf:"varint,2,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
	ResultPerPage        *int32   `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage" json:"result_per_page,omitempty"`
	Samples              []int32  `protobuf:"varint,4,rep,name=samples" json:"samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil && m.PageNumber != nil {
		return *m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil && m.ResultPerPage != nil {
		return *m.ResultPerPage
	}
	return 0
}

func (m *SearchRequest) GetSamples() []int32 {
	if m != nil {
		return m.Samples
	}
	return nil
}

type SearchResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x31, 0x0e, 0x82, 0x40,
	0x10, 0x85, 0xe1, 0x00, 0x12, 0xe3, 0x18, 0xd4, 0x6c, 0x2c, 0xb6, 0x93, 0x50, 0x18, 0x2a, 0x8f,
	0x62, 0xc8, 0x7a, 0x00, 0xb2, 0xea, 0x0b, 0x16, 0xc0, 0x2e, 0x33, 0x6c, 0xe1, 0x0d, 0x3c, 0xb6,
	0x01, 0x42, 0xf9, 0x7f, 0x33, 0xc5, 0x23, 0x7a, 0xa3, 0x73, 0x37, 0xcf, 0x6e, 0x74, 0xc5, 0x2f,
	0xa2, 0xec, 0x01, 0xcb, 0xaf, 0x8f, 0xc1, 0x10, 0x20, 0xa3, 0x3a, 0x53, 0x3a, 0x04, 0xf0, 0x57,
	0x47, 0x79, 0x5c, 0xee, 0xcc, 0x12, 0xea, 0x42, 0x7b, 0x6f, 0x1b, 0xd4, 0x7d, 0xe8, 0x9e, 0x60,
	0x1d, 0xe7, 0x51, 0x99, 0x1a, 0x9a, 0xe8, 0x3e, 0x8b, 0xba, 0xd2, 0x91, 0x21, 0xa1, 0x1d, 0x6b,
	0x0f, 0xae, 0xa7, 0x83, 0x4e, 0xe6, 0xa7, 0x6c, 0xe1, 0x0a, 0x5c, 0xd9, 0x06, 0x4a, 0xd3, 0x56,
	0x6c, 0xe7, 0x5b, 0x88, 0xde, 0xe4, 0x49, 0x99, 0x9a, 0x35, 0x8b, 0x13, 0x1d, 0xd6, 0x25, 0xe2,
	0x5d, 0x2f, 0xf8, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xe4, 0x51, 0x3c, 0xa9, 0x00, 0x00, 0x00,
}
